# SCRIPT
^https:\/\/[a-z.\-0-9]*(bilivideo.com|akamaized.net)\/.* url script-request-header https://github.com/DevonJi/CDN-change/blob/main/bilibili_cdn_change.js

# MITM
hostname = *.akamaized.net, *.bilivideo.com
